export const COLUMN_ORDER = [
  "site_logging_movement",
  "date",
  "movement_type",
  "bin",
  "shipped_to_received_from",
  "shipped_received_type",
  "shipped_to_received_from_if_not_found",
  "item",
  "item_description",
  "asset_type",
  "model_if_not_found_in_list",
  "asset_type_if_not_found_in_list",
  "owner",
  "quantity",
  "rollforward_quantity",
  "logged_by",
  "ics_comment",
  "serial",
  "jira_ticket",
  "po",
  "rma",
  "mrb",
  "carrier",
  "carrier_tracking",
  "logged_in_ns",
  "netsuite_transaction_id",
] as const;

export const COLUMN_LABELS: Record<string, string> = {
  site_logging_movement: "SITE LOGGING MOVEMENT",
  date: "DATE",
  movement_type: "MOVEMENT TYPE",
  bin: "BIN",
  shipped_to_received_from: "SHIPPED TO / RECEIVED FROM",
  shipped_received_type: "SHIPPED / RECEIVED TYPE",
  shipped_to_received_from_if_not_found: "SHIPPED TO / RECEIVED FROM IF NOT FOUND",
  item: "ITEM #",
  item_description: "ITEM DESCRIPTION",
  asset_type: "ASSET TYPE",
  model_if_not_found_in_list: "MODEL # IF NOT FOUND IN LIST",
  asset_type_if_not_found_in_list: "ASSET TYPE IF NOT FOUND IN LIST",
  owner: "OWNER",
  quantity: "QUANTITY",
  rollforward_quantity: "ROLLFORWARD QUANTITY",
  logged_by: "LOGGED BY",
  ics_comment: "ICS COMMENT",
  serial: "SERIAL #",
  jira_ticket: "JIRA TICKET #",
  po: "PO #",
  rma: "RMA #",
  mrb: "MRB #",
  carrier: "CARRIER",
  carrier_tracking: "CARRIER TRACKING #",
  logged_in_ns: "LOGGED IN NS?",
  netsuite_transaction_id: "NETSUITE TRANSACTION ID",
};

export const SORT_OPTIONS = [
  { value: "date", label: "DATE" },
  { value: "movement_type", label: "MOVEMENT TYPE" },
  { value: "bin", label: "BIN" },
  { value: "asset_type", label: "ASSET TYPE" },
  { value: "item", label: "ITEM #" },
  { value: "owner", label: "OWNER" },
] as const;

export function toSpreadsheetLabel(key: string): string {
  return COLUMN_LABELS[key] ?? key.replace(/_/g, " ").toUpperCase();
}
